# Common User Parameters
SAMPLE_RATE = 10 #Hz
BASELINE_NOISE = 0.2
RUN_LENGTH = 15 # minutes  

# Peak shape parameters 
DEFAULT_PEAK_WIDTH = 0.18
SIGNAL_MULIPLIER = 5 #multipier for signal
DEFAULT_BASE_ASYMMETRY = 1.03
ASYMMETRY_DEPENDENCE_ON_RETENTION_TIME = 1.004
WIDENING_CONSTANT = 1.01

# Noise Parameters
OVERALL_HEIGHT_RANDOM_NOISE = .007 #relative size of noise variation in peak height
INDIVIDUAL_HEIGHT_RANDOM_NOISE = 0.002
RETENTION_TIME_RANDOM_OFFSET_MAX = 0.003
INDIVIDUAL_RETENTION_TIME_RANDOM_NOISE = 0.001